server:
  port: 8080

# Database Configuartion
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/quickpik"
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  

#File upload config
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
        

# Image upload path
user-image-path: "C:\\Users\\soura\\Documents\\e-commerce project\\images\\users"
category-image-path: "C:\\Users\\soura\\Documents\\e-commerce project\\images\\categories"
product-image-path: "C:\\Users\\soura\\Documents\\e-commerce project\\images\\products"

#Role Id
role.admin.id: "f27a14dc-7d57-4cd9-b1d5-b7b4ec3007a2"
role.normal.id: "ed6baf4d-59cc-4c16-b23e-6513b081f3b8"

# Google Login
googleClientId: "504051870278-cjbe0hldbt6b8e29qou379chgv9dkt6c.apps.googleusercontent.com"
googleSecret: "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"
newPassword: "R9%)@SR7:+>Jj(KY"

# JWT Secret Key
application:
  security:
    jwt:
     secret-key: "e1dfc184c8a2b317c9c37e7dc44af7b9fa2fbe9d808f56e2587df159c7ba6dacd356eab6720f44ef2897eba9778764c3269414e99442b545d1fc091e6d895bab"
     expiration: "86400" # 1 day
     refresh-token:
      expiration: "604800" # 7 day